### ISSUE TITLE
vtable support 

### ISSUE THREAD

**Issue by jrossi** [zombiezen/go-sqlite#15]
Been playing around with this project and was wondering if you had plans to implement virtual table support?

**Comment by zombiezen** [comment]
I didn't have any immediate plans, since I haven't really used the feature much myself. Looking at https://sqlite.org/vtab.html, the API surface area is pretty large, so I would want to approach it pretty deliberately to make sure the Go API is reasonable.

**Comment by anacrolix** [comment]
I have been using `go.riyazali.net/sqlite` mentioned also here https://github.com/crawshaw/sqlite/issues/98#issuecomment-778309079. I suspect I can load extensions produced by that library just fine with crawshaw.io/sqlite. Would I be correct in assuming that I can't load C shared extensions with zombiezen/go-sqlite because it's not actually calling in to or expecting actual C interfaces (due to modernc/sqlite)?

Would there be any way to make this work if that's correct? Could I somehow build extensions to be loadable by this module/modernc/sqlite? Thanks!

**Comment by zombiezen** [comment]
You are correct that you would not be able to load a shared object with this library: the C symbols would not be present, because modernc transpiles them to Go.

IIUC, the package you mention is a way of writing Go code that connects into the SQLite C API. If you can port the usages over to calling the `modernc.org/sqlite/lib` calls (which are 1:1 transpilations), then you should be able to reuse that work. I'm not sure how feasible that is.

**Comment by anacrolix** [comment]
Thanks!

**Comment by anacrolix** [comment]
It's a bit outside my experience to add this support through the lens of modern.org/sqlite. It's several layers of obscurity. I did eventually run into [performance issues](https://github.com/riyaz-ali/sqlite/issues/20) in a Go-to-C extension, callbacks from C to Go put a lot of stress on the Go scheduler. This wouldn't occur for a pure-Go implementation, but you would also be losing the ability to load the extension from C as a loadable extension.

**Comment by anacrolix** [comment]
Thanks for your great work on this!

**Comment by zombiezen** [comment]
You're welcome! Feel free to pull down the latest `main` and try it out before I cut the release. I've written some example code to verify the functionality and get a rough feel for the API, but additional feedback (even if it's just "yup, looks right") would be very appreciated.
