### ISSUE TITLE
Online Backup API?

### ISSUE THREAD

**Issue by delaneyj** [zombiezen/go-sqlite#47]
Search the code but unless I'm missing something the [Online Backup API](https://www.sqlite.org/c3ref/backup_finish.html#sqlite3backupinit) isn't supported.  However there is [a commit of it](https://github.com/zombiezen/go-sqlite/commit/e49cdaf3a5dc2b4a3d03a420684bad2e6fe064c4) that seems to be missing now.  @zombiezen what's the status?

**Comment by zombiezen** [comment]
When I forked, I basically did a full rewrite but preserved history to properly acknowledge the work that was being built upon. I overlooked the Online Backup API since I hadn't had experience using it personally.

Looks like a simple enough API to provide. I can hack that out in the next week or so.
